version: '3.7'

services:

  sample:
    container_name: sense
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/economics'
      - '/economics/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
